import type { Product } from "@/domain/products/types";

/*
 * Catalogue factice : les 16 produits présents dans les lignes de commande de
 * src/domain/orders/fixtures.ts, avec les mêmes ids et noms (vérifié par
 * test/domain/products/fixtures.test.ts). Prix cohérents avec les totaux de ligne
 * (par kg pour les produits au poids, par pièce sinon). Déterministe : dates fixes.
 */
const UPDATED = "2026-09-06T18:00:00.000Z";

export const productsFixtures: readonly Product[] = [
  {
    id: "prd-0001",
    name: "Carottes",
    category: "vegetables",
    unit: "g",
    priceCents: 290,
    available: true,
    stockQuantity: 24000,
    updatedAt: UPDATED,
  },
  {
    id: "prd-0002",
    name: "Pommes Gala",
    category: "fruits",
    unit: "g",
    priceCents: 350,
    available: true,
    stockQuantity: 18000,
    updatedAt: UPDATED,
  },
  {
    id: "prd-0003",
    name: "Bananes",
    category: "fruits",
    unit: "g",
    priceCents: 250,
    available: true,
    stockQuantity: 1500,
    updatedAt: UPDATED,
  },
  {
    id: "prd-0004",
    name: "Tomates cœur de bœuf",
    category: "vegetables",
    unit: "g",
    priceCents: 700,
    available: true,
    stockQuantity: 6400,
    updatedAt: UPDATED,
  },
  {
    id: "prd-0005",
    name: "Courgettes",
    category: "vegetables",
    unit: "g",
    priceCents: 350,
    available: true,
    stockQuantity: 9000,
    updatedAt: UPDATED,
  },
  {
    id: "prd-0006",
    name: "Salade batavia",
    category: "vegetables",
    unit: "piece",
    priceCents: 180,
    available: true,
    stockQuantity: 30,
    updatedAt: UPDATED,
  },
  {
    id: "prd-0007",
    name: "Avocat",
    category: "fruits",
    unit: "piece",
    priceCents: 150,
    available: true,
    stockQuantity: 8,
    updatedAt: UPDATED,
  },
  {
    id: "prd-0008",
    name: "Citron",
    category: "fruits",
    unit: "piece",
    priceCents: 60,
    available: true,
    stockQuantity: 120,
    updatedAt: UPDATED,
  },
  {
    id: "prd-0009",
    name: "Fraises (barquette)",
    category: "fruits",
    unit: "piece",
    priceCents: 350,
    available: false,
    stockQuantity: 0,
    updatedAt: UPDATED,
  },
  {
    id: "prd-0010",
    name: "Pommes de terre",
    category: "vegetables",
    unit: "g",
    priceCents: 200,
    available: true,
    stockQuantity: 40000,
    updatedAt: UPDATED,
  },
  {
    id: "prd-0011",
    name: "Oignons jaunes",
    category: "vegetables",
    unit: "g",
    priceCents: 240,
    available: true,
    stockQuantity: 12000,
    updatedAt: UPDATED,
  },
  {
    id: "prd-0012",
    name: "Poireaux",
    category: "vegetables",
    unit: "g",
    priceCents: 450,
    available: true,
    stockQuantity: 5600,
    updatedAt: UPDATED,
  },
  {
    id: "prd-0013",
    name: "Melon",
    category: "fruits",
    unit: "piece",
    priceCents: 390,
    available: true,
    stockQuantity: 14,
    updatedAt: UPDATED,
  },
  {
    id: "prd-0014",
    name: "Raisin",
    category: "fruits",
    unit: "g",
    priceCents: 700,
    available: true,
    stockQuantity: 3200,
    updatedAt: UPDATED,
  },
  {
    id: "prd-0015",
    name: "Concombre",
    category: "vegetables",
    unit: "piece",
    priceCents: 130,
    available: true,
    stockQuantity: 45,
    updatedAt: UPDATED,
  },
  {
    id: "prd-0016",
    name: "Poivron rouge",
    category: "vegetables",
    unit: "piece",
    priceCents: 180,
    available: false,
    stockQuantity: 3,
    updatedAt: UPDATED,
  },
];
