import type { Product } from "@/domain/products/types";

/*
 * Catalogue factice : les 16 produits présents dans les lignes de commande de
 * src/domain/orders/fixtures.ts, avec les mêmes ids, noms et unités (vérifié par
 * test/domain/products/fixtures.test.ts). Prix cohérents avec les totaux de ligne.
 * Déterministe : dates fixes. Origines, calibres et saisons sont inventés pour la
 * démo (septembre).
 */
const UPDATED = "2026-09-06T18:00:00.000Z";

type Seed = Omit<Product, "updatedAt" | "imageUrl"> &
  Partial<Pick<Product, "updatedAt" | "imageUrl">>;

const p = (seed: Seed): Product => ({
  imageUrl: null,
  updatedAt: UPDATED,
  ...seed,
});

export const productsFixtures: readonly Product[] = [
  p({
    id: "prd-0001",
    name: "Carottes",
    variety: "Nantaise",
    category: "vegetable",
    unit: "g",
    priceCents: 290,
    unitWeightGrams: null,
    container: "crate",
    originCountry: "FR",
    originRegion: "Landes",
    caliber: { minMm: 20, maxMm: 35 },
    organic: true,
    inSeason: true,
    available: true,
    visible: true,
    stockQuantity: 24000,
    illustration: "🥕",
  }),
  p({
    id: "prd-0002",
    name: "Pommes",
    variety: "Gala",
    category: "fruit",
    unit: "g",
    priceCents: 350,
    unitWeightGrams: null,
    container: "tray",
    originCountry: "FR",
    originRegion: "Val de Loire",
    caliber: { minMm: 70, maxMm: 80 },
    organic: false,
    inSeason: true,
    available: true,
    visible: true,
    stockQuantity: 18000,
    illustration: "🍎",
  }),
  p({
    id: "prd-0003",
    name: "Bananes",
    variety: "Cavendish",
    category: "fruit",
    unit: "g",
    priceCents: 250,
    unitWeightGrams: null,
    container: "parcel",
    originCountry: "EC",
    originRegion: null,
    caliber: null,
    organic: true,
    inSeason: false,
    available: true,
    visible: true,
    stockQuantity: 1500,
    illustration: "🍌",
  }),
  p({
    id: "prd-0004",
    name: "Tomates",
    variety: "Cœur de bœuf",
    category: "vegetable",
    unit: "g",
    priceCents: 700,
    unitWeightGrams: null,
    container: "tray",
    originCountry: "FR",
    originRegion: "Provence",
    caliber: { minMm: 80, maxMm: 100 },
    organic: false,
    inSeason: true,
    available: true,
    visible: true,
    stockQuantity: 6400,
    illustration: "🍅",
  }),
  p({
    id: "prd-0005",
    name: "Courgettes",
    variety: null,
    category: "vegetable",
    unit: "g",
    priceCents: 350,
    unitWeightGrams: null,
    container: "crate",
    originCountry: "FR",
    originRegion: "Provence",
    caliber: { minMm: 14, maxMm: 21 },
    organic: true,
    inSeason: true,
    available: true,
    visible: true,
    stockQuantity: 9000,
    illustration: "🥒",
  }),
  p({
    id: "prd-0006",
    name: "Salade",
    variety: "Batavia",
    category: "vegetable",
    unit: "piece",
    priceCents: 180,
    unitWeightGrams: 350,
    container: "none",
    originCountry: "FR",
    originRegion: "Île-de-France",
    caliber: null,
    organic: false,
    inSeason: true,
    available: true,
    visible: true,
    stockQuantity: 30,
    illustration: "🥬",
  }),
  p({
    id: "prd-0007",
    name: "Avocat",
    variety: "Hass",
    category: "fruit",
    unit: "piece",
    priceCents: 150,
    unitWeightGrams: 200,
    container: "tray",
    originCountry: "PE",
    originRegion: null,
    caliber: { minMm: 60, maxMm: 70 },
    organic: false,
    inSeason: false,
    available: true,
    visible: true,
    stockQuantity: 8,
    illustration: "🥑",
  }),
  p({
    id: "prd-0008",
    name: "Citron",
    variety: "Primofiori",
    category: "fruit",
    unit: "piece",
    priceCents: 60,
    unitWeightGrams: 120,
    container: "bag",
    originCountry: "ES",
    originRegion: "Murcie",
    caliber: { minMm: 53, maxMm: 62 },
    organic: false,
    inSeason: false,
    available: true,
    visible: true,
    stockQuantity: 120,
    illustration: "🍋",
  }),
  p({
    id: "prd-0009",
    name: "Fraises",
    variety: "Gariguette",
    category: "fruit",
    unit: "piece",
    priceCents: 350,
    unitWeightGrams: 250,
    container: "tray",
    originCountry: "FR",
    originRegion: "Lot-et-Garonne",
    caliber: null,
    organic: false,
    inSeason: false,
    available: false,
    visible: true,
    stockQuantity: 0,
    illustration: "🍓",
  }),
  p({
    id: "prd-0010",
    name: "Pommes de terre",
    variety: "Agata",
    category: "vegetable",
    unit: "g",
    priceCents: 200,
    unitWeightGrams: null,
    container: "bag",
    originCountry: "FR",
    originRegion: "Picardie",
    caliber: { minMm: 40, maxMm: 60 },
    organic: false,
    inSeason: true,
    available: true,
    visible: true,
    stockQuantity: 40000,
    illustration: "🥔",
  }),
  p({
    id: "prd-0011",
    name: "Oignons",
    variety: "Jaunes",
    category: "vegetable",
    unit: "g",
    priceCents: 240,
    unitWeightGrams: null,
    container: "bag",
    originCountry: "FR",
    originRegion: "Bretagne",
    caliber: { minMm: 50, maxMm: 70 },
    organic: true,
    inSeason: true,
    available: true,
    visible: true,
    stockQuantity: 12000,
    illustration: "🧅",
  }),
  p({
    id: "prd-0012",
    name: "Poireaux",
    variety: null,
    category: "vegetable",
    unit: "g",
    priceCents: 450,
    unitWeightGrams: null,
    container: "crate",
    originCountry: "FR",
    originRegion: "Nord",
    caliber: { minMm: 25, maxMm: 40 },
    organic: false,
    inSeason: true,
    available: true,
    visible: true,
    stockQuantity: 5600,
    illustration: "🌱",
  }),
  p({
    id: "prd-0013",
    name: "Melon",
    variety: "Charentais",
    category: "fruit",
    unit: "piece",
    priceCents: 390,
    unitWeightGrams: 900,
    container: "crate",
    originCountry: "FR",
    originRegion: "Cavaillon",
    caliber: { minMm: 110, maxMm: 130 },
    organic: false,
    inSeason: true,
    available: true,
    visible: true,
    stockQuantity: 0,
    illustration: "🍈",
  }),
  p({
    id: "prd-0014",
    name: "Raisin",
    variety: "Muscat",
    category: "fruit",
    unit: "g",
    priceCents: 700,
    unitWeightGrams: null,
    container: "tray",
    originCountry: "IT",
    originRegion: "Pouilles",
    caliber: null,
    organic: false,
    inSeason: true,
    available: true,
    visible: true,
    stockQuantity: 3200,
    illustration: "🍇",
  }),
  p({
    id: "prd-0015",
    name: "Concombre",
    variety: null,
    category: "vegetable",
    unit: "piece",
    priceCents: 130,
    unitWeightGrams: 400,
    container: "none",
    originCountry: "FR",
    originRegion: "Île-de-France",
    caliber: null,
    organic: true,
    inSeason: true,
    available: true,
    visible: true,
    stockQuantity: 45,
    illustration: "🥒",
  }),
  p({
    id: "prd-0016",
    name: "Poivron",
    variety: "Rouge",
    category: "vegetable",
    unit: "piece",
    priceCents: 180,
    unitWeightGrams: 180,
    container: "tray",
    originCountry: "ES",
    originRegion: "Almería",
    caliber: { minMm: 70, maxMm: 90 },
    organic: false,
    inSeason: true,
    available: false,
    visible: false,
    stockQuantity: 3,
    illustration: "🫑",
  }),
];
